import { expectedRecognition } from "../../test/utils/expected-recognition";
import { test } from "vitest";

test.for([
  {
    source: import.meta.glob<string>("../../../assets/recognitions/raw/track/Acorn Heights.png", {
      eager: true,
      import: `default`,
    }),
    expected: {
      coins: "00",
      lap: "1",
      laps: "3",
      pause: false,
      shrooms: "3",
      time: "0:00.000",
      timeYellow: false,
      track: "Acorn Heights",
    },
  },
  {
    source: import.meta.glob<string>("../../../assets/recognitions/raw/track/Airship Fortress.png", {
      eager: true,
      import: `default`,
    }),
    expected: {
      coins: "00",
      lap: "1",
      laps: "3",
      pause: false,
      shrooms: "3",
      time: "0:00.000",
      timeYellow: false,
      track: "Airship Fortress",
    },
  },
  {
    source: import.meta.glob<string>("../../../assets/recognitions/raw/track/Boo Cinema.png", {
      eager: true,
      import: `default`,
    }),
    expected: {
      coins: "00",
      lap: "1",
      laps: "3",
      pause: false,
      shrooms: "3",
      time: "0:00.000",
      timeYellow: false,
      track: "Boo Cinema",
    },
  },
  {
    source: import.meta.glob<string>("../../../assets/recognitions/raw/track/Bowser's Castle.png", {
      eager: true,
      import: `default`,
    }),
    expected: {
      coins: "00",
      lap: "1",
      laps: "3",
      pause: false,
      shrooms: "3",
      time: "0:00.000",
      timeYellow: false,
      track: "Bowser's Castle",
    },
  },
  {
    source: import.meta.glob<string>("../../../assets/recognitions/raw/track/Cheep Cheep Falls.png", {
      eager: true,
      import: `default`,
    }),
    expected: {
      coins: "00",
      lap: "1",
      laps: "3",
      pause: false,
      shrooms: "3",
      time: "0:00.000",
      timeYellow: false,
      track: "Cheep Cheep Falls",
    },
  },
  {
    source: import.meta.glob<string>("../../../assets/recognitions/raw/track/Choco Mountain.png", {
      eager: true,
      import: `default`,
    }),
    expected: {
      coins: "00",
      lap: "1",
      laps: "3",
      pause: false,
      shrooms: "3",
      time: "0:00.000",
      timeYellow: false,
      track: "Choco Mountain",
    },
  },
  {
    source: import.meta.glob<string>("../../../assets/recognitions/raw/track/Crown City.png", {
      eager: true,
      import: `default`,
    }),
    expected: {
      coins: "00",
      lap: "1",
      laps: "3",
      pause: false,
      shrooms: "3",
      time: "0:00.000",
      timeYellow: false,
      track: "Crown City",
    },
  },
  {
    source: import.meta.glob<string>("../../../assets/recognitions/raw/track/Dandelion Depths.png", {
      eager: true,
      import: `default`,
    }),
    expected: {
      coins: "00",
      lap: "1",
      laps: "3",
      pause: false,
      shrooms: "3",
      time: "0:00.000",
      timeYellow: false,
      track: "Dandelion Depths",
    },
  },
  {
    source: import.meta.glob<string>("../../../assets/recognitions/raw/track/Desert Hills.png", {
      eager: true,
      import: `default`,
    }),
    expected: {
      coins: "00",
      lap: "1",
      laps: "3",
      pause: false,
      shrooms: "3",
      time: "0:00.000",
      timeYellow: false,
      track: "Desert Hills",
    },
  },
  {
    source: import.meta.glob<string>("../../../assets/recognitions/raw/track/Dino Dino Jungle.png", {
      eager: true,
      import: `default`,
    }),
    expected: {
      coins: "00",
      lap: "1",
      laps: "3",
      pause: false,
      shrooms: "3",
      time: "0:00.000",
      timeYellow: false,
      track: "Dino Dino Jungle",
    },
  },
  {
    source: import.meta.glob<string>("../../../assets/recognitions/raw/track/DK Pass.png", {
      eager: true,
      import: `default`,
    }),
    expected: {
      coins: "00",
      lap: "1",
      laps: "3",
      pause: false,
      shrooms: "3",
      time: "0:00.000",
      timeYellow: false,
      track: "DK Pass",
    },
  },
  {
    source: import.meta.glob<string>("../../../assets/recognitions/raw/track/DK Spaceport.png", {
      eager: true,
      import: `default`,
    }),
    expected: {
      coins: "00",
      lap: "1",
      laps: "6",
      pause: false,
      shrooms: "3",
      time: "0:00.000",
      timeYellow: false,
      track: "DK Spaceport",
    },
  },
  {
    source: import.meta.glob<string>("../../../assets/recognitions/raw/track/Dry Bones Burnout.png", {
      eager: true,
      import: `default`,
    }),
    expected: {
      coins: "00",
      lap: "1",
      laps: "3",
      pause: false,
      shrooms: "3",
      time: "0:00.000",
      timeYellow: false,
      track: "Dry Bones Burnout",
    },
  },
  {
    source: import.meta.glob<string>("../../../assets/recognitions/raw/track/Faraway Oasis.png", {
      eager: true,
      import: `default`,
    }),
    expected: {
      coins: "00",
      lap: "1",
      laps: "3",
      pause: false,
      shrooms: "3",
      time: "0:00.000",
      timeYellow: false,
      track: "Faraway Oasis",
    },
  },
  {
    source: import.meta.glob<string>("../../../assets/recognitions/raw/track/Great ؟ Block Ruins.png", {
      eager: true,
      import: `default`,
    }),
    expected: {
      coins: "00",
      lap: "1",
      laps: "3",
      pause: false,
      shrooms: "3",
      time: "0:00.000",
      timeYellow: false,
      track: "Great ? Block Ruins",
    },
  },
  {
    source: import.meta.glob<string>("../../../assets/recognitions/raw/track/Koopa Troopa Beach.png", {
      eager: true,
      import: `default`,
    }),
    expected: {
      coins: "00",
      lap: "1",
      laps: "5",
      pause: false,
      shrooms: "3",
      time: "0:00.000",
      timeYellow: false,
      track: "Koopa Troopa Beach",
    },
  },
  {
    source: import.meta.glob<string>("../../../assets/recognitions/raw/track/Mario Bros. Circuit.png", {
      eager: true,
      import: `default`,
    }),
    expected: {
      coins: "00",
      lap: "1",
      laps: "3",
      pause: false,
      shrooms: "3",
      time: "0:00.000",
      timeYellow: false,
      track: "Mario Bros. Circuit",
    },
  },
  {
    source: import.meta.glob<string>("../../../assets/recognitions/raw/track/Mario Circuit.png", {
      eager: true,
      import: `default`,
    }),
    expected: {
      coins: "00",
      lap: "1",
      laps: "3",
      pause: false,
      shrooms: "3",
      time: "0:00.000",
      timeYellow: false,
      track: "Mario Circuit",
    },
  },
  {
    source: import.meta.glob<string>("../../../assets/recognitions/raw/track/Moo Moo Meadows.png", {
      eager: true,
      import: `default`,
    }),
    expected: {
      coins: "00",
      lap: "1",
      laps: "3",
      pause: false,
      shrooms: "3",
      time: "0:00.000",
      timeYellow: false,
      track: "Moo Moo Meadows",
    },
  },
  {
    source: import.meta.glob<string>("../../../assets/recognitions/raw/track/Peach Beach.png", {
      eager: true,
      import: `default`,
    }),
    expected: {
      coins: "00",
      lap: "1",
      laps: "3",
      pause: false,
      shrooms: "3",
      time: "0:00.000",
      timeYellow: false,
      track: "Peach Beach",
    },
  },
  {
    source: import.meta.glob<string>("../../../assets/recognitions/raw/track/Peach Stadium.png", {
      eager: true,
      import: `default`,
    }),
    expected: {
      coins: "00",
      lap: "1",
      laps: "3",
      pause: false,
      shrooms: "3",
      time: "0:00.000",
      timeYellow: false,
      track: "Peach Stadium",
    },
  },
  {
    source: import.meta.glob<string>("../../../assets/recognitions/raw/track/Rainbow Road.png", {
      eager: true,
      import: `default`,
    }),
    expected: {
      coins: "00",
      lap: "1",
      laps: "4",
      pause: false,
      shrooms: "3",
      time: "0:00.000",
      timeYellow: false,
      track: "Rainbow Road",
    },
  },
  {
    source: import.meta.glob<string>("../../../assets/recognitions/raw/track/Salty Salty Speedway.png", {
      eager: true,
      import: `default`,
    }),
    expected: {
      coins: "00",
      lap: "1",
      laps: "3",
      pause: false,
      shrooms: "3",
      time: "0:00.000",
      timeYellow: false,
      track: "Salty Salty Speedway",
    },
  },
  {
    source: import.meta.glob<string>("../../../assets/recognitions/raw/track/Shy Guy Bazaar.png", {
      eager: true,
      import: `default`,
    }),
    expected: {
      coins: "00",
      lap: "1",
      laps: "3",
      pause: false,
      shrooms: "3",
      time: "0:00.000",
      timeYellow: false,
      track: "Shy Guy Bazaar",
    },
  },
  {
    source: import.meta.glob<string>("../../../assets/recognitions/raw/track/Sky-High Sundae.png", {
      eager: true,
      import: `default`,
    }),
    expected: {
      coins: "00",
      lap: "1",
      laps: "3",
      pause: false,
      shrooms: "3",
      time: "0:00.000",
      timeYellow: false,
      track: "Sky-High Sundae",
    },
  },
  {
    source: import.meta.glob<string>("../../../assets/recognitions/raw/track/Starview Peak.png", {
      eager: true,
      import: `default`,
    }),
    expected: {
      coins: "00",
      lap: "1",
      laps: "3",
      pause: false,
      shrooms: "3",
      time: "0:00.000",
      timeYellow: false,
      track: "Starview Peak",
    },
  },
  {
    source: import.meta.glob<string>("../../../assets/recognitions/raw/track/Toad's Factory.png", {
      eager: true,
      import: `default`,
    }),
    expected: {
      coins: "00",
      lap: "1",
      laps: "3",
      pause: false,
      shrooms: "3",
      time: "0:00.000",
      timeYellow: false,
      track: "Toad's Factory",
    },
  },
  {
    source: import.meta.glob<string>("../../../assets/recognitions/raw/track/Wario Shipyard.png", {
      eager: true,
      import: `default`,
    }),
    expected: {
      coins: "00",
      lap: "1",
      laps: "3",
      pause: false,
      shrooms: "3",
      time: "0:00.000",
      timeYellow: false,
      track: "Wario Shipyard",
    },
  },
  {
    source: import.meta.glob<string>("../../../assets/recognitions/raw/track/Wario Stadium.png", {
      eager: true,
      import: `default`,
    }),
    expected: {
      coins: "00",
      lap: "1",
      laps: "3",
      pause: false,
      shrooms: "3",
      time: "0:00.000",
      timeYellow: false,
      track: "Wario Stadium",
    },
  },
  {
    source: import.meta.glob<string>("../../../assets/recognitions/raw/track/Whistlestop Summit.png", {
      eager: true,
      import: `default`,
    }),
    expected: {
      coins: "00",
      lap: "1",
      laps: "3",
      pause: false,
      shrooms: "3",
      time: "0:00.000",
      timeYellow: false,
      track: "Whistlestop Summit",
    },
  },
  /* Ver.1.8.0 - Free Update */
  {
    source: import.meta.glob<string>("../../../assets/recognitions/raw/track/SNES Choco Island 1.png", {
      eager: true,
      import: `default`,
    }),
    expected: {
      coins: "00",
      lap: "1",
      laps: "5",
      pause: false,
      shrooms: "3",
      time: "0:00.000",
      timeYellow: false,
      track: "SNES Choco Island 1",
    },
  },
  {
    source: import.meta.glob<string>("../../../assets/recognitions/raw/track/SNES Choco Island 2.png", {
      eager: true,
      import: `default`,
    }),
    expected: {
      coins: "00",
      lap: "1",
      laps: "5",
      pause: false,
      shrooms: "3",
      time: "0:00.000",
      timeYellow: false,
      track: "SNES Choco Island 2",
    },
  },
  {
    source: import.meta.glob<string>("../../../assets/recognitions/raw/track/SNES Ghost Valley 1.png", {
      eager: true,
      import: `default`,
    }),
    expected: {
      coins: "00",
      lap: "1",
      laps: "5",
      pause: false,
      shrooms: "3",
      time: "0:00.000",
      timeYellow: false,
      track: "SNES Ghost Valley 1",
    },
  },
  {
    source: import.meta.glob<string>("../../../assets/recognitions/raw/track/SNES Ghost Valley 2.png", {
      eager: true,
      import: `default`,
    }),
    expected: {
      coins: "00",
      lap: "1",
      laps: "5",
      pause: false,
      shrooms: "3",
      time: "0:00.000",
      timeYellow: false,
      track: "SNES Ghost Valley 2",
    },
  },
  {
    source: import.meta.glob<string>("../../../assets/recognitions/raw/track/SNES Koopa Beach 1.png", {
      eager: true,
      import: `default`,
    }),
    expected: {
      coins: "00",
      lap: "1",
      laps: "5",
      pause: false,
      shrooms: "3",
      time: "0:00.000",
      timeYellow: false,
      track: "SNES Koopa Beach 1",
    },
  },
  {
    source: import.meta.glob<string>("../../../assets/recognitions/raw/track/SNES Mario Circuit 1.png", {
      eager: true,
      import: `default`,
    }),
    expected: {
      coins: "00",
      lap: "1",
      laps: "5",
      pause: false,
      shrooms: "3",
      time: "0:00.000",
      timeYellow: false,
      track: "SNES Mario Circuit 1",
    },
  },
  {
    source: import.meta.glob<string>("../../../assets/recognitions/raw/track/SNES Mario Circuit 2.png", {
      eager: true,
      import: `default`,
    }),
    expected: {
      coins: "00",
      lap: "1",
      laps: "5",
      pause: false,
      shrooms: "3",
      time: "0:00.000",
      timeYellow: false,
      track: "SNES Mario Circuit 2",
    },
  },
  {
    source: import.meta.glob<string>("../../../assets/recognitions/raw/track/SNES Mario Circuit 3.png", {
      eager: true,
      import: `default`,
    }),
    expected: {
      coins: "00",
      lap: "1",
      laps: "5",
      pause: false,
      shrooms: "3",
      time: "0:00.000",
      timeYellow: false,
      track: "SNES Mario Circuit 3",
    },
  },
  {
    source: import.meta.glob<string>("../../../assets/recognitions/raw/track/SNES Ghost Valley 3.png", {
      eager: true,
      import: `default`,
    }),
    expected: {
      coins: "00",
      lap: "1",
      laps: "5",
      pause: false,
      shrooms: "3",
      time: "0:00.000",
      timeYellow: false,
      track: "SNES Ghost Valley 3",
    },
  },
  {
    source: import.meta.glob<string>("../../../assets/recognitions/raw/track/SNES Vanilla Lake 1.png", {
      eager: true,
      import: `default`,
    }),
    expected: {
      coins: "00",
      lap: "1",
      laps: "5",
      pause: false,
      shrooms: "3",
      time: "0:00.000",
      timeYellow: false,
      track: "SNES Vanilla Lake 1",
    },
  },
])("validate $source", async (params) => {
  await expectedRecognition(params, false);
});
