import { expectedRecognition } from "../../test/utils/expected-recognition";
import { test } from "vitest";

test.for([
  {
    source: import.meta.glob<string>("../../../assets/recognitions/raw/coins/00.png", {
      eager: true,
      import: `default`,
    }),
    expected: {
      coins: "00",
      lap: "1",
      laps: "3",
      pause: false,
      shrooms: "3",
      time: "0:38.722",
      timeYellow: false,
      track: "Mario Bros. Circuit",
    },
  },
  {
    source: import.meta.glob<string>("../../../assets/recognitions/raw/coins/01.png", {
      eager: true,
      import: `default`,
    }),
    expected: {
      coins: "01",
      lap: "1",
      laps: "3",
      pause: false,
      shrooms: "3",
      time: "0:59.557",
      timeYellow: false,
      track: "Mario Bros. Circuit",
    },
  },
  {
    source: import.meta.glob<string>("../../../assets/recognitions/raw/coins/02.png", {
      eager: true,
      import: `default`,
    }),
    expected: {
      coins: "02",
      lap: "1",
      laps: "3",
      pause: false,
      shrooms: "3",
      time: "1:22.932",
      timeYellow: false,
      track: "Mario Bros. Circuit",
    },
  },
  {
    source: import.meta.glob<string>("../../../assets/recognitions/raw/coins/03.png", {
      eager: true,
      import: `default`,
    }),
    expected: {
      coins: "03",
      lap: "2",
      laps: "3",
      pause: false,
      shrooms: "3",
      time: "2:16.101",
      timeYellow: false,
      track: "Mario Bros. Circuit",
    },
  },
  {
    source: import.meta.glob<string>("../../../assets/recognitions/raw/coins/04.png", {
      eager: true,
      import: `default`,
    }),
    expected: {
      coins: "04",
      lap: "2",
      laps: "3",
      pause: false,
      shrooms: "3",
      time: "2:33.226",
      timeYellow: false,
      track: "Mario Bros. Circuit",
    },
  },
  {
    source: import.meta.glob<string>("../../../assets/recognitions/raw/coins/05.png", {
      eager: true,
      import: `default`,
    }),
    expected: {
      coins: "05",
      lap: "2",
      laps: "3",
      pause: false,
      shrooms: "3",
      time: "2:54.831",
      timeYellow: false,
      track: "Mario Bros. Circuit",
    },
  },
  {
    source: import.meta.glob<string>("../../../assets/recognitions/raw/coins/06.png", {
      eager: true,
      import: `default`,
    }),
    expected: {
      coins: "06",
      lap: "3",
      laps: "3",
      pause: false,
      shrooms: "3",
      time: "3:28.393",
      timeYellow: false,
      track: "Mario Bros. Circuit",
    },
  },
  {
    source: import.meta.glob<string>("../../../assets/recognitions/raw/coins/07.png", {
      eager: true,
      import: `default`,
    }),
    expected: {
      coins: "07",
      lap: "3",
      laps: "3",
      pause: false,
      shrooms: "3",
      time: "3:43.310",
      timeYellow: false,
      track: "Mario Bros. Circuit",
    },
  },
  {
    source: import.meta.glob<string>("../../../assets/recognitions/raw/coins/08.png", {
      eager: true,
      import: `default`,
    }),
    expected: {
      coins: "08",
      lap: "3",
      laps: "3",
      pause: false,
      shrooms: "3",
      time: "3:57.000",
      timeYellow: false,
      track: "Mario Bros. Circuit",
    },
  },
  {
    source: import.meta.glob<string>("../../../assets/recognitions/raw/coins/09.png", {
      eager: true,
      import: `default`,
    }),
    expected: {
      coins: "09",
      lap: "3",
      laps: "3",
      pause: false,
      shrooms: "3",
      time: "4:16.042",
      timeYellow: false,
      track: "Mario Bros. Circuit",
    },
  },
  {
    source: import.meta.glob<string>("../../../assets/ideas/coins/10.png", { eager: true, import: `default` }),
    expected: {
      coins: "10",
      lap: "1",
      laps: "3",
      pause: false,
      shrooms: "3",
      time: "1:03.560",
      timeYellow: false,
      track: "Mario Bros. Circuit",
    },
  },
  {
    source: import.meta.glob<string>("../../../assets/ideas/coins/11.png", { eager: true, import: `default` }),
    expected: {
      coins: "11",
      lap: "2",
      laps: "3",
      pause: false,
      shrooms: "3",
      time: "1:36.072",
      timeYellow: false,
      track: "Mario Bros. Circuit",
    },
  },
  {
    source: import.meta.glob<string>("../../../assets/ideas/coins/12.png", { eager: true, import: `default` }),
    expected: {
      coins: "12",
      lap: "2",
      laps: "3",
      pause: false,
      shrooms: "3",
      time: "1:50.513",
      timeYellow: false,
      track: "Mario Bros. Circuit",
    },
  },
  {
    source: import.meta.glob<string>("../../../assets/ideas/coins/13.png", { eager: true, import: `default` }),
    expected: {
      coins: "13",
      lap: "2",
      laps: "3",
      pause: false,
      shrooms: "3",
      time: "2:02.241",
      timeYellow: false,
      track: "Mario Bros. Circuit",
    },
  },
  {
    source: import.meta.glob<string>("../../../assets/ideas/coins/14.png", { eager: true, import: `default` }),
    expected: {
      coins: "14",
      lap: "2",
      laps: "3",
      pause: false,
      shrooms: "3",
      time: "2:24.347",
      timeYellow: false,
      track: "Mario Bros. Circuit",
    },
  },
  {
    source: import.meta.glob<string>("../../../assets/ideas/coins/15.png", { eager: true, import: `default` }),
    expected: {
      coins: "15",
      lap: "3",
      laps: "3",
      pause: false,
      shrooms: "3",
      time: "2:56.906",
      timeYellow: false,
      track: "Mario Bros. Circuit",
    },
  },
  {
    source: import.meta.glob<string>("../../../assets/ideas/coins/16.png", { eager: true, import: `default` }),
    expected: {
      coins: "16",
      lap: "3",
      laps: "3",
      pause: false,
      shrooms: "3",
      time: "3:09.444",
      timeYellow: false,
      track: "Mario Bros. Circuit",
    },
  },
  {
    source: import.meta.glob<string>("../../../assets/ideas/coins/17.png", { eager: true, import: `default` }),
    expected: {
      coins: "17",
      lap: "3",
      laps: "3",
      pause: false,
      shrooms: "3",
      time: "3:21.759",
      timeYellow: false,
      track: "Mario Bros. Circuit",
    },
  },
  {
    source: import.meta.glob<string>("../../../assets/ideas/coins/18.png", { eager: true, import: `default` }),
    expected: {
      coins: "18",
      lap: "3",
      laps: "3",
      pause: false,
      shrooms: "0",
      time: "2:15.625",
      timeYellow: false,
      track: "Mario Bros. Circuit",
    },
  },
  {
    source: import.meta.glob<string>("../../../assets/ideas/coins/19.png", { eager: true, import: `default` }),
    expected: {
      coins: "19",
      lap: "3",
      laps: "3",
      pause: false,
      shrooms: "0",
      time: "2:25.405",
      timeYellow: false,
      track: "Mario Bros. Circuit",
    },
  },
  {
    source: import.meta.glob<string>("../../../assets/ideas/coins/20.png", { eager: true, import: `default` }),
    expected: {
      coins: "20",
      lap: "3",
      laps: "3",
      pause: false,
      shrooms: "0",
      time: "2:45.178",
      timeYellow: false,
      track: "Mario Bros. Circuit",
    },
  },
])("Validate $source", async (params) => {
  await expectedRecognition(params, true);
});
