name: Prepare the project
description: Install all the necessary dependencies

runs:
  using: composite
  steps:
    - name: Setup pnpm
      # The cache feature is not officially yet released, so using a specific commit that has it.
      uses: pnpm/action-setup@1e1c8eafbd745f64b1ef30a7d7ed7965034c486c
      with:
        cache: true

    - name: Setup node
      uses: actions/setup-node@v5
      with:
        node-version: 24

    - name: Install npm dependencies
      shell: bash
      run: pnpm install

    - name: Install playwright system dependencies
      shell: bash
      run: ./node_modules/.bin/playwright install chromium --with-deps
