name: Release
run-name: Release - ${{ github.ref_name }}

on:
  workflow_dispatch: # Allow to manually trigger the pipeline

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  check:
    runs-on: ubuntu-24.04
    steps:
      - name: Must be on release branch
        if: github.ref_name != 'release'
        run: |
          echo "You can release only on the release branch"
          exit 1

      - uses: actions/checkout@v5

      - uses: ./.github/actions/prepare

      - uses: ./.github/actions/build

      - uses: ./.github/actions/release
